# Generated by Django 3.2.7 on 2021-09-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=100)),
                ('bookprice', models.IntegerField(default=1)),
                ('bookauthor', models.CharField(max_length=50)),
                ('bookimage', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=100)),
                ('totalbooks', models.IntegerField(default=0)),
                ('storeimage', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'store',
            },
        ),
    ]
