# Generated by Django 3.2.7 on 2021-10-06 13:53

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('phone', models.CharField(max_length=10)),
                ('otp_count', models.IntegerField(default=0, help_text="Number of otp's sent.")),
                ('otp_request_datetime', models.DateTimeField(auto_now=True)),
                ('validated', models.BooleanField(default=False, help_text='If True, otp is validated.')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='0000000000', max_length=10, null=True, validators=[user.models.User.validate_phone_number]),
        ),
    ]
